application: oneandagain
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Static assets
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /
  static_files: templates/index.html
  upload: templates/index\.html

# Endpoints handler
- url: /_ah/spi/.*
  script: whisky_api.APPLICATION

libraries:
- name: pycrypto
  version: latest
